version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11
      - image: mongo
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test